### ISSUE TITLE
Best practice for long-running client?

### ISSUE THREAD

**Issue by shadz3rg** [basis-company/nats.php#29]
What is intended method to implement production-ready RPC server using this lib?
Is it possible to bootstrap some loop (using roadrunner?) with good stability and proper connection-outage handling?

Other libs make use of language-specific features, so PHP way is kinda tricky
https://github.com/nats-io/nats.py/blob/main/examples/service.py#L59

**Comment by nekufa** [comment]
Hello, @shadz3rg!

We were living with coroutines (amphp and then swoole) for several monthes and rolled back to standard approach.
In this case background processors are console scripts.

So, we simply run isolate thread that consumes thread with unlimited limit
https://github.com/basis-company/nats.php#jetstream-api-usage

Usage example is here:
https://github.com/basis-company/framework.php/blob/master/php/Job/Nats/Consume.php#L47

**Comment by shadz3rg** [comment]
@nekufa Thanks for reply!
Was there any particular problems with coroutines? 
I tried connection via https://github.com/amphp/socket (v2  8.1 fibers + event-loop) with basic protocol handler, it worked pretty stable for testing purposes, not sure about production though.

**Comment by nekufa** [comment]
@shadz3rg there were no problems, but you need to keep in mind that coroutines enhance processing time due better cpu utilization, so we decided that lower processing time is better for our case. 
operation system thread context switch works good and there is no needs to reimplement it using event-loop on php side. php runtime overhead is not to much, so it's better to run operation system threads. that's why we do not use coroutines anymore.

**Comment by shadz3rg** [comment]
Thanks again!
