### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by andy-g** [basis-company/nats.php#3]
Is there any chance that this package could be made compatible with PHP 7? We'd be open to contribute to any required changes if need be - but would first want to know if you'd be open to support older PHP versions.

We're looking at introducing NATS in our environment, but would like to be able to integrate it with our legacy systems which are running PHP 7.2.

**Comment by nekufa** [comment]
@andy-g hello!

This client uses a lot of php8 specific features (typed properties, readonly properties, constructor property definition, etc..) and that's why source code is simple. I don't think there is a reason to remove this.

You can simply use legacy repejota client https://github.com/repejota/phpnats
If you need jetstream - you can write your own wrapper. It uses core protocol with specific subjects and messages.
Checkout jetstream api reference - https://docs.nats.io/reference/reference-protocols/nats_api_reference

If you need any help with wrapper - you can use official slack and #jetstream or #php channel.
It's developer friendly environment :)

**Comment by nekufa** [comment]
Of course you can fork this project and remove class property types, function argument types and do some extra definitions and property set in constructor. there are not a lot to do - whole library is about 2k lines

**Comment by andy-g** [comment]
Thanks @nekufa, yes, I'm already on the slack channels & contributed to the NATS Prometheus exporter, so have really enjoyed the developer friendly environment.

I was wondering about the older clients. So I could still use the older clients to publish & even subscribe to subjects (even subjects that are part of streams), but PHP 8 clients could then take advantage of the Jetstream specific functionality?

**Comment by nekufa** [comment]
Yep, you are right!

By the way, you can also publish to a jetstream stream using legacy client - it's a simple message publish to a subject.

If you need to use jetstream features - check out jetstream api reference. For example, writing to a bucket is a message sent to the specific subject.
